# Cheat Sheet (Highlights from Course)
### Missing Values
* Map missing values and replace with 0

In [3]:
# load modules
import numpy as np

# create list of lists and include a couple of missing values
list1 = [[np.nan,np.inf,1],[2,2,2],[3,3,3]]

# convert list to array
arr1 = np.array(list1)

# show array with missing values
print(arr1)

# map/flag for missing values
missing_flag = np.isnan(arr1) | np.isinf(arr1)

# replace missing values with 0
arr1[missing_flag] = 0

# show result
print(arr1)

[[nan inf  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
[[0. 0. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


### Numpy Objects
* Numpy aranges are the same as ranges but far quicker, use these if you care about performance when storing or manipulating data.

In [6]:
# create numpy array
arr1 = np.arange(1, 5)
arr1

array([1, 2, 3, 4])